default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  <<: *default
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] || 'localhost' %>
  port: <%= ENV['PGPORT'] || '5432' %>
  database: <%= ENV['PG_TEST_DATABASE'] || 'tb_core_test' %>
